# Generated by Django 5.2.9 on 2026-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LongQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ques', models.CharField(max_length=200)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=200)),
                ('opt_1', models.CharField(max_length=120)),
                ('opt_2', models.CharField(max_length=120)),
                ('opt_3', models.CharField(max_length=120)),
                ('opt_4', models.CharField(max_length=120)),
                ('ans', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='True_False',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ques', models.CharField(max_length=200)),
                ('ans', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('personal_pc', models.CharField(max_length=100)),
                ('personal_phn', models.CharField(max_length=100)),
            ],
        ),
    ]
