# Generated by Django 5.2.9 on 2026-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educational', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longques',
            name='subject',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='true_false',
            name='subject',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
