# Generated by Django 5.2.11 on 2026-02-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educational', '0002_longques_subject_true_false_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longques',
            old_name='Ques',
            new_name='ques',
        ),
        migrations.RenameField(
            model_name='true_false',
            old_name='Ques',
            new_name='ques',
        ),
    ]
