# Generated by Django 5.2.11 on 2026-03-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educational', '0003_rename_ques_longques_ques_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longques',
            old_name='ques',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='mcq',
            old_name='ans',
            new_name='Answers',
        ),
        migrations.RenameField(
            model_name='mcq',
            old_name='opt_1',
            new_name='Option_1',
        ),
        migrations.RenameField(
            model_name='mcq',
            old_name='opt_2',
            new_name='Option_2',
        ),
        migrations.RenameField(
            model_name='mcq',
            old_name='opt_3',
            new_name='Option_3',
        ),
        migrations.RenameField(
            model_name='mcq',
            old_name='opt_4',
            new_name='Option_4',
        ),
        migrations.RenameField(
            model_name='mcq',
            old_name='ques',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='true_false',
            old_name='ques',
            new_name='Question',
        ),
    ]
